import { mkdir, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { FAULTS } from "../tests/mutation/faults.ts";

/**
 * MR38 evidence: run the whole acceptance suite once per controlled fault
 * and record exactly which named tests fail (kill) it. Slow by design
 * (one full suite per fault); `bun run test` runs the fast killer check.
 */
const root = fileURLToPath(new URL("../", import.meta.url));
const files = (await readdir(resolve(root, "tests/acceptance")))
  .filter((name) => name.endsWith(".test.ts") && name !== "mr-mutation.test.ts")
  .map((name) => `tests/acceptance/${name}`)
  .sort();

const lines = [
  "# Mutation report (MR38)",
  "",
  "Generated by `bun run test:mutation`: each controlled fault from `tests/mutation/faults.ts` is",
  "applied to the real source at load time, then the acceptance suite runs. Killers are the tests",
  "that fail. A surviving fault fails this script.",
  "",
];
let survivors = 0;
for (const fault of FAULTS) {
  const run = Bun.spawnSync(["bun", "test", "--preload", "./tests/mutation/preload.ts", ...files], {
    cwd: root,
    env: { ...process.env, MUTATION: fault.id },
    stdout: "pipe",
    stderr: "pipe",
  });
  const out = `${run.stdout.toString()}${run.stderr.toString()}`;
  const killers = [...out.matchAll(/^\(fail\) (.+?)(?: \[[\d.]+m?s\])?$/gm)].map((m) => m[1] ?? "");
  if (killers.length === 0) survivors += 1;
  lines.push(`## ${fault.id}`, "", `${fault.description} (\`${fault.file}\`).`, "");
  lines.push(killers.length === 0 ? "- **SURVIVED**" : `Killed by ${killers.length} test(s):`, "");
  for (const killer of killers) lines.push(`- ${killer}`);
  lines.push("");
}
await mkdir(resolve(root, "reports"), { recursive: true });
await writeFile(resolve(root, "reports/mutation-report.md"), lines.join("\n"));
console.log(`${FAULTS.length} faults, ${survivors} survived → reports/mutation-report.md`);
if (survivors > 0) process.exitCode = 1;
