import { writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CHANGE_KINDS } from "../src/core/change.ts";
import { randomPair, sweep } from "../tests/support/ot/generated.ts";
import { runMatrix, summarize } from "../tests/support/ot/matrix.ts";
import { seedBudget } from "../tests/support/random.ts";
import type { SimStats } from "../tests/support/sim.ts";
import { simulateHistory } from "../tests/support/sim.ts";

/**
 * Writes the operation-pair coverage report (MR34/MR35): case counts per
 * ordered primitive pair, their outcome classes, and the geometry classes
 * reached. The numbers are evidence of what ran, not a proof of the algebra.
 */
const root = fileURLToPath(new URL("../", import.meta.url));
const cases = runMatrix();
const cells = summarize(cases);
const failures = cases.filter((c) => c.outcome === "failure");
const issues = failures.map((f) => `${f.id}: ${f.problems.join("; ")}`);

const lines: string[] = [
  "# Operation-pair coverage",
  "",
  "Generated by `bun run ot:report` from `tests/support/ot/` (fixture, spec-derived oracle,",
  "identity sequence model). Each ordered pair of positioned single primitives runs in both",
  "origin precedences; compatible pairs are checked for TP1, the independent oracle, both",
  "branch inverse laws, serialization, argument order, and input isolation.",
  "",
  `Total cases: ${cases.length}. Failures: ${failures.length}.`,
  "",
  "| A \\ B | " + CHANGE_KINDS.join(" | ") + " |",
  "| --- | " + CHANGE_KINDS.map(() => "---:").join(" | ") + " |",
];
for (const x of CHANGE_KINDS) {
  const row = CHANGE_KINDS.map((y) => {
    const cell = cells.get(`${x}×${y}`);
    const o = cell?.outcomes ?? {};
    return `${cell?.cases ?? 0} (${o["compatible"] ?? 0}/${o["conflict"] ?? 0}/${o["refusal"] ?? 0})`;
  });
  lines.push(`| ${x} | ${row.join(" | ")} |`);
}
lines.push("", "Cell format: cases (compatible/conflict/refusal).", "", "## Geometry classes", "");
const geometries = new Map<string, number>();
for (const c of cases) geometries.set(c.geometry, (geometries.get(c.geometry) ?? 0) + 1);
lines.push("| Geometry | Cases |", "| --- | ---: |");
for (const [name, count] of [...geometries].sort()) lines.push(`| ${name} | ${count} |`);
lines.push("", "## Geometries per cell", "");
for (const [cell, data] of [...cells].sort()) {
  const parts = Object.entries(data.geometries)
    .sort()
    .map(([name, count]) => `${name} ×${count}`);
  lines.push(`- **${cell}**: ${parts.join(", ")}`);
}
lines.push("", "## Generated composite pairs (MR36)", "");
lines.push(
  "| Sweep | Seeds | Compatible | Conflict | Refusal | Failure |",
  "| --- | ---: | ---: | ---: | ---: | ---: |",
);
const seeds = seedBudget(3000, "ALGEBRA");
for (const [name, dense] of [
  ["random documents", false],
  ["dense paragraph", true],
] as const) {
  const tally = sweep(seeds, (r) => randomPair(r, dense));
  const o = tally.outcomes;
  lines.push(
    `| ${name} | ${seeds.length} | ${o.compatible} | ${o.conflict} | ${o.refusal} | ${o.failure} |`,
  );
  issues.push(...tally.failures.map((failure) => `${name}: ${failure}`));
}
const stats: SimStats[] = [];
const histories = seedBudget(120, "HISTORY");
for (const seed of histories) {
  const failure = simulateHistory(seed, 60, stats);
  if (failure !== null) issues.push(`history seed ${seed}: ${failure}`);
}
lines.push("", `## Simulated histories (MR37): ${histories.length} seeds × 60 steps`, "");
lines.push("| Event | Count |", "| --- | ---: |");
for (const key of Object.keys(stats[0] ?? {}) as (keyof SimStats)[])
  lines.push(`| ${key} | ${stats.reduce((sum, s) => sum + s[key], 0)} |`);
if (issues.length > 0) lines.push("", "## Failures", "", ...issues.map((issue) => `- ${issue}`));
await mkdir(resolve(root, "reports"), { recursive: true });
await writeFile(resolve(root, "reports/ot-pair-coverage.md"), lines.join("\n") + "\n");
console.log(`${cases.length} pair cases, ${issues.length} failures → reports/ot-pair-coverage.md`);
if (issues.length > 0) process.exitCode = 1;
